tmf: Add interface to clear persistent data of analysis modules
eclipse-tracecompass/org.eclipse.tracecompass pull request #106
Opened 2024-06-14 13:27 UTC by bhufmann

- Implement method for TmfStateSystemAnalysisModule
- This allows to delete state systems from the analysis module.
If state system is open, it will close the state system files first
before deleting the file. Otherwise delete the file directly.
- Calling methods are responsible to re-trigger the analysis execution

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2024-06-18 17:48 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statesystem/TmfStateSystemAnalysisModule.java
> +        if (fStateSystem != null) {
fStateSystem is null when analysis has not been scheduled even if the state system file exists, and hence the state system is not deleted

2024-06-28 15:29 UTC, MatthewKhouzam commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
> +     * @since 9.4
I think we need more doc here

2024-07-02 14:34 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
> +     * @since 9.4
Makes sense.

2024-07-11 18:58 UTC, PatrickTasse requested changes

2024-07-11 18:58 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
> +     * used to re-executed analysis without having to close the trace.
re-execute (the || an) analysis module

2024-07-11 21:13 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
> +     * used to re-executed analysis without having to close the trace.
Done

2024-07-17 13:03 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statesystem/TmfStateSystemAnalysisModule.java
> +                    if (htFile.exists()) {
Makes sense.

2024-07-17 13:13 UTC, MatthewKhouzam approved these changes

2024-07-17 13:29 UTC, merged