tmf: Add support for json-schema to configuration types
eclipse-tracecompass/org.eclipse.tracecompass pull request #141
Opened 2024-08-30 17:10 UTC by bhufmann

https://json-schema.org/

[Added] support for json-schema to configuration types

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2024-09-03 12:37 UTC, bhufmann commented
FYI @abhinava-ericsson

2024-10-15 17:30 UTC, PatrickTasse requested changes

2024-10-15 17:30 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSourceType.java
> +    /**
Missing blank line before

2024-10-15 17:30 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSourceType.java
> +     * A string containing a json-schema describing the query parameters
Gets a file containing...

2024-10-15 17:30 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSourceType.java
> +     * Note: Use either {@link #getConfigParamDescriptors()} or {@link #getSchemaFile()}
For the user, they don't know which is to be used. I would suggest:
Note: If the schema file is null, use {@link #getConfigParamDescriptors()} instead.

Should we also add a note in that other method?
Note: Use this method if {@link #getSchemaFile()} returns null.

2024-10-15 18:14 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSourceType.java
> +    /**
Done

2024-10-15 18:33 UTC, PatrickTasse approved these changes

2024-10-15 18:52 UTC, merged