Expose the clock and frequency in CtfTmfTrace
eclipse-tracecompass/org.eclipse.tracecompass pull request #155
Opened 2024-09-23 15:01 UTC by siwei-zhang-work

The frequency of the CtfTmfTrace is currently exposed in an indirect way using cyclesToNanos(). BUt sometimes there is the need to get direct frequency.

[Added] public method to get clock info in CTFTmfTrace 
[Added] public method to get frequency in CTFClock

2024-09-23 17:34 UTC, MatthewKhouzam commented
Hi Siwei, any thoughts on complementing getEnvironment with the frequency? It would require less code and no API changes.

2024-09-24 08:37 UTC, siwei-zhang-work commented
> Hi Siwei, any thoughts on complementing getEnvironment with the frequency? It would require less code and no API changes.

But the getEnvironment() refers to a specific `env` block in the metadata, and complementing getEnvironment() still requires exposing frequency from the CTFClock. I changed to adding the frequency in the getProperties(), and the frequency is exposed the same way as time offset. Does this seem cleaner? Otherwise I'll add the frequency in the getEnvironment().

2024-09-26 15:57 UTC, MatthewKhouzam commented
getEnvironment currently refers to `env` but it means all data that is not in events. I would recommend using it for all static information, also I will add get environment to TmfTrace. Trace Event should have this for metadata too. Maybe we can get a second opinion, but I would not add a new api for this instead of enhancing the output.

2024-09-27 12:10 UTC, siwei-zhang-work commented
> getEnvironment currently refers to `env` but it means all data that is not in events. I would recommend using it for all static information, also I will add get environment to TmfTrace. Trace Event should have this for metadata too. Maybe we can get a second opinion, but I would not add a new api for this instead of enhancing the output.

Sounds good, done.

2024-09-27 14:51 UTC, MatthewKhouzam approved these changes

2024-09-27 14:52 UTC, MatthewKhouzam requested changes
Please make sure you're not breaking the API. @deprecate instead.

2024-09-30 13:48 UTC, MatthewKhouzam approved these changes

2024-09-30 16:59 UTC, bhufmann approved these changes
LGTM. Thanks!

2024-09-30 16:59 UTC, merged