tmf: Add parent ID and creation configuration to IDataProviderDescriptor
eclipse-tracecompass/org.eclipse.tracecompass pull request #165
Opened 2024-10-15 21:16 UTC by bhufmann

This will allow to show configuration parameters that were used to create a data provider to the user, as well as, group data providers using the parent ID.

[Added] parent ID and creation configuration to IDataProviderDescriptor

Bernd Hufmann <bernd.hufmann@ericsson.com>

2024-10-16 14:16 UTC, PatrickTasse requested changes

2024-10-16 14:16 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +     * @param buidder
one more try ;)

2024-10-16 14:16 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +                +  ", fCreationConfiguration" + fCreationConfiguration
missing = ?

2024-10-16 14:16 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +
extra blank line

2024-10-16 14:16 UTC, PatrickTasse commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +
extra blank line

2024-10-16 15:30 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +                +  ", fCreationConfiguration" + fCreationConfiguration
Done

2024-10-16 15:30 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +
Done

2024-10-16 15:32 UTC, bhufmann commented on tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
> +
Done

2024-10-17 17:48 UTC, PatrickTasse approved these changes

2024-10-17 17:49 UTC, merged