profiling.core: make callstack api
eclipse-tracecompass/org.eclipse.tracecompass pull request #23
Opened 2024-02-22 17:28 UTC by arfio

This commit makes the new callstack api, moving necessary classes to provisional packages and adding it to the API.

2024-02-23 20:28 UTC, MatthewKhouzam approved these changes

2024-03-07 13:41 UTC, MatthewKhouzam approved these changes
Looks good to me.

2024-03-20 19:44 UTC, bhufmann requested changes
Beside the main comment below, I noticed that there are API that were already in the mainline callstack packages that were also in the incubator callstack packages. I think Genevieve added this classes/interface to make the mainlining easier. For example, if you compare the following 2 packages you find duplicate classes:
`org.eclipse.tracecompass.analysis.profiling.core.callstack`  
`org.eclipse.tracecompass.internal.provisional.analysis.profiling.core.callstack'

Also, the interface `IFlameChartProvider` exists twice in the same plug-in.

What is your plan handling these duplications? Please let me know. 

2024-03-20 19:44 UTC, bhufmann commented on analysis/org.eclipse.tracecompass.analysis.profiling.core/META-INF/MANIFEST.MF
> + org.eclipse.tracecompass.internal.provisional.analysis.profiling.core.base,
provisional APIs are APIs that are proposed and are supposed to be made public in the future. However, they still need to be marked as internal in the MANIFEST.MF (x-internal:=true or x-friends if there are any). If this PR is to make the APIs public, then the package name cannot contain provisional.

This applies for all relevant changed lines in the MANIFEST.MF files.

2024-03-26 18:10 UTC, arfio commented
Once this path is merged, we can deprecate the old versions of the duplicated classes as well as the old callstack API. Then, after some time has passed, we will be able to remove the old API and replace it completely.

2024-03-28 19:01 UTC, bhufmann approved these changes
Thanks for this contribution. It looks good to me.  You can merge it, since you're a committer now.

2024-03-29 01:20 UTC, merged